################################################################################
# This is an unpublished work of SAIC.
# Copyright (c) 2023 SAIC. All Rights Reserved.
################################################################################

[versions]

# See also '<root>\platform\build.gradle' for additoinal version definitions
# via BOM dependency declarations and version constraint usages.

assertj = "3.27.6"
controlsfx = "11.0.3"
dependencyAnalysis-gradlePlugin = "3.5.1"
h2 = "2.4.240"
hibernate = "7.2.0.Final"
jackson = "2.20.1"
# `jacoco` is used in project-convention.gradle.kts
jacoco = "0.8.14"
jakartaAnnotation = "3.0.0"
jakartaInject = "2.0.1.MR"
jakartaPersistence = "3.2.0"
javafx = "19.0.2.1"
javafx-gradlePlugin = "0.1.0"
jetbrains-annotations = "26.0.2-1"
jreleaser-gradlePlugin = "1.22.0"
kotlin = "2.2.21"
junit = "5.14.1"
jvmDependencyConflict-gradlePlugin = "2.5"
jvmDownGrader-gradlePlugin = "1.3.4"
slf4j = "2.0.17"
spring = "6.2.15"
springboot = "3.5.9"
springboot-constraint = "(,4)"
testfx = "4.0.18"
testfx-monocle = "jdk-12.0.1+2"
versionsCheck-gradlePlugin = "0.53.0"

[libraries]

[libraries.assertj-bom]
module = "org.assertj:assertj-bom"
version.ref = "assertj"

[libraries.assertj-core]
module = "org.assertj:assertj-core"
version.ref = "assertj"

[libraries.controlsfx]
module = "org.controlsfx:controlsfx"
version.ref = "controlsfx"

[libraries.dependencyAnalysis-gradlePlugin-dependency]
module = "com.autonomousapps.dependency-analysis:com.autonomousapps.dependency-analysis.gradle.plugin"
version.ref = "dependencyAnalysis-gradlePlugin"

[libraries.h2]
module = "com.h2database:h2"
version.ref = "h2"

[libraries.hibernate-core]
module = "org.hibernate.orm:hibernate-core"
version.ref = "hibernate"

[libraries.jackson-annotations]
module = "com.fasterxml.jackson.core:jackson-annotations"

[libraries.jackson-bom]
module = "com.fasterxml.jackson:jackson-bom"
version.ref = "jackson"

[libraries.jackson-databind]
module = "com.fasterxml.jackson.core:jackson-databind"

[libraries.jakarta-annotation]
module = "jakarta.annotation:jakarta.annotation-api"
version.ref = "jakartaAnnotation"

[libraries.jakarta-inject]
module = "jakarta.inject:jakarta.inject-api"
version.ref = "jakartaInject"

[libraries.jakarta-persistence]
module = "jakarta.persistence:jakarta.persistence-api"
version.ref = "jakartaPersistence"

[libraries.jakarta-xmlbinding-api]
module = "jakarta.xml.bind:jakarta.xml.bind-api"

[libraries.jakarta-xmlbinding-impl]
module = "org.glassfish.jaxb:jaxb-runtime"

[libraries.javafx-base]
module = "org.openjfx:javafx-base"
version.ref = "javafx"

[libraries.javafx-controls]
module = "org.openjfx:javafx-controls"
version.ref = "javafx"

[libraries.javafx-graphics]
module = "org.openjfx:javafx-graphics"
version.ref = "javafx"

[libraries.jetbrains-annotations]
module = "org.jetbrains:annotations"
version.ref = "jetbrains-annotations"

[libraries.junit-bom]
module = "org.junit:junit-bom"
version.ref = "junit"

[libraries.junit-jupiter-api]
module = "org.junit.jupiter:junit-jupiter-api"

[libraries.jvmDependencyConflict-gradlePlugin-dependency]
module = "org.gradlex:jvm-dependency-conflict-resolution"
version.ref = "jvmDependencyConflict-gradlePlugin"

[libraries.kotlin-bom]
module = "org.jetbrains.kotlin:kotlin-bom"
version.ref = "kotlin"

[libraries.kotlin-gradlePlugin-dependency]
module = "org.jetbrains.kotlin:kotlin-gradle-plugin"
version.ref = "kotlin"

[libraries.kotlin-spring-gradlePlugin-dependency]
module = "org.jetbrains.kotlin:kotlin-allopen"
version.ref = "kotlin"

[libraries.slf4j-api]
module = "org.slf4j:slf4j-api"
version.ref = "slf4j"

[libraries.slf4j-jdk14]
module = "org.slf4j:slf4j-jdk14"
version.ref = "slf4j"

[libraries.spring-bom]
module = "org.springframework:spring-framework-bom"
version.ref = "spring"

[libraries.spring-beans]
module = "org.springframework:spring-beans"

[libraries.spring-context]
module = "org.springframework:spring-context"

[libraries.spring-core]
module = "org.springframework:spring-core"

[libraries.springboot]
module = "org.springframework.boot:spring-boot"

[libraries.springboot-autoconfigure]
module = "org.springframework.boot:spring-boot-autoconfigure"

[libraries.springboot-bom]
module = "org.springframework.boot:spring-boot-dependencies"
version.ref = "springboot"

[libraries.springboot-starter]
module = "org.springframework.boot:spring-boot-starter"

[libraries.springboot-starter-logging]
module = "org.springframework.boot:spring-boot-starter-logging"

[libraries.testfx-core]
module = "org.testfx:testfx-core"
version.ref = "testfx"

[libraries.testfx-junit5]
module = "org.testfx:testfx-junit5"
version.ref = "testfx"

[libraries.testfx-monocle]
module = "org.testfx:openjfx-monocle"
version.ref = "testfx-monocle"

# TODO BENTO-13: Delete these unused bundles?
[bundles]

javafx = [
    "javafx-base",
    "javafx-controls",
    "javafx-graphics",
]

testfx = ["testfx-core", "testfx-junit5", "testfx-monocle"]

[plugins]

[plugins.dependencyAnalysis-gradlePlugin]
id = "com.autonomousapps.dependency-analysis"
version.ref = "dependencyAnalysis-gradlePlugin"

[plugins.javafx-gradlePlugin]
id = "org.openjfx.javafxplugin"
version.ref = "javafx-gradlePlugin"

[plugins.jvmDownGrader-gradlePlugin]
id = "xyz.wagyourtail.jvmdowngrader"
version.ref = "jvmDownGrader-gradlePlugin"

[plugins.jvmDependencyConflict-detection-gradlePlugin]
id = "org.gradlex.jvm-dependency-conflict-detection"
version.ref = "jvmDependencyConflict-gradlePlugin"

[plugins.jvmDependencyConflict-resolution-gradlePlugin]
id = "org.gradlex.jvm-dependency-conflict-resolution"
version.ref = "jvmDependencyConflict-gradlePlugin"

[plugins.jreleaser-gradlePlugin]
id = "org.jreleaser"
version.ref = "jreleaser-gradlePlugin"

[plugins.springboot-gradlePlugin]
id = "org.springframework.boot"
version.ref = "springboot"

[plugins.versionsCheck-gradlePlugin]
id = "com.github.ben-manes.versions"
version.ref = "versionsCheck-gradlePlugin"
